//! Agent / AI-authored PR detection for Tier-1 prioritization.

use crate::bot::quality::SignalBudget;

#[derive(Debug, Clone, Default)]
pub struct AgentSignal {
    pub is_agent: bool,
    pub reasons: Vec<String>,
}

/// Heuristic detection of agent-authored PRs (Cursor, Claude, Copilot, Devin, etc.).
pub fn detect_agent_pr(
    pr_title: &str,
    pr_body: &str,
    commit_messages: &[String],
    author: &str,
) -> AgentSignal {
    let mut reasons = Vec::new();
    let blob = format!(
        "{}\n{}\n{}\n{}",
        pr_title,
        pr_body,
        author,
        commit_messages.join("\n")
    )
    .to_ascii_lowercase();

    let markers = [
        ("co-authored-by: copilot", "Copilot co-author"),
        ("co-authored-by: claude", "Claude co-author"),
        ("co-authored-by: chatgpt", "ChatGPT co-author"),
        ("co-authored-by: cursor", "Cursor co-author"),
        ("generated by cursor", "Cursor generation marker"),
        ("generated with claude", "Claude generation marker"),
        ("devin", "Devin agent marker"),
        ("@cursor", "Cursor mention"),
        ("aider", "Aider agent marker"),
        ("continue.dev", "Continue agent marker"),
    ];
    for (needle, reason) in markers {
        if blob.contains(needle) {
            reasons.push(reason.into());
        }
    }

    let author_l = author.to_ascii_lowercase();
    if author_l.contains("[bot]")
        || author_l.ends_with("-bot")
        || author_l.contains("dependabot")
        || author_l.contains("renovate")
    {
        // Dependency bots are not coding agents — skip agent mode.
        return AgentSignal {
            is_agent: false,
            reasons: vec![],
        };
    }

    AgentSignal {
        is_agent: !reasons.is_empty(),
        reasons,
    }
}

/// Tighten budgets toward Tier-1 when agent-authored.
pub fn agent_signal_budget(base: SignalBudget) -> SignalBudget {
    SignalBudget {
        max_blocking: base.max_blocking.saturating_add(5),
        max_warning: base.max_warning.min(5),
        max_info: 1,
    }
}

/// Cap LLM nit suggestions on agent PRs (Tier-1 first).
pub fn agent_llm_issue_cap(is_agent: bool) -> usize {
    if is_agent {
        4
    } else {
        12
    }
}

pub fn agent_badge(signal: &AgentSignal) -> Option<String> {
    if !signal.is_agent {
        return None;
    }
    Some(format!(
        "> [!NOTE]\n\
         > **Agent-authored PR** — Tier-1 detectors prioritized; LLM nits capped.\n\
         > Signals: {}",
        signal.reasons.join(" · ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_copilot_trailer() {
        let s = detect_agent_pr(
            "feat",
            "body",
            &["Co-authored-by: Copilot <copilot@github.com>".into()],
            "alice",
        );
        assert!(s.is_agent);
    }

    #[test]
    fn ignores_dependabot() {
        let s = detect_agent_pr("deps", "", &[], "dependabot[bot]");
        assert!(!s.is_agent);
    }

    #[test]
    fn agent_caps_llm_nits() {
        assert_eq!(agent_llm_issue_cap(true), 4);
        assert_eq!(agent_llm_issue_cap(false), 12);
    }
}
